ecommerce/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'
urlpatterns = [
    path('', views.store, name="store"),
	path('cart/', views.cart, name="cart"),
	path('checkout/', views.checkout, name="checkout"),
	path('update_item/', views.updateItem, name="update_item"),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Customer(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=200, null=True)
    price = models.FloatField()
    digital = models.BooleanField(default=False)
    image = models.ImageField(upload_to = 'product/', null=True, blank=True)

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=True)
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total
    
    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name
    
    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

class ShippingAddres(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    pincode = models.IntegerField(null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

store/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .models import *

import json


# Create your views here.

def store(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cat_total':0, 'get_cat_items':0}
        cartItems = order['get_cart_items']

    products = Product.objects.all()
    context = {'products':products, 'cartItems':cartItems}
    return render(request, 'store/store.html', context)


def cart(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
    else:
        items = []
        order = {'get_cat_total':0, 'get_cat_items':0}
    context = {'items':items, 'order':order}
    return render(request, 'store/cart.html', context)


def checkout(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
    else:
        items = []
        order = {'get_cat_total':0, 'get_cat_items':0}
    context = {'items':items, 'order':order}
    return render(request, 'store/checkout.html', context)


def updateItem(request):
    data = json.loads(request.body)
    productID = data['productID']
    action = data['action']
    print('Action :', action)
    print('ProductID :', productID)

    customer = request.user.customer
    product = Product.objects.get(id=productID)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)
    
    if action =='add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)
    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()
        
    return JsonResponse('Item was added', safe=False)

store/templates/store/cart.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="box-element">
                <a  class="btn btn-outline-dark" href="{% url 'store:store' %}">&#x2190; Continue Shopping</a>
                <br>
                <br>
                <table class="table">
                    <tr>
                        <th><h5>Items : <strong>{{order.get_cart_items}}</strong></h5></th>
                        <th><h5>Total :<strong> ₹ {{order.get_cart_total|floatformat:2}}</strong></h5></th>
                        <th>
                            <a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'store:checkout' %}">Checkout</a>
                        </th>
                    </tr>
                </table>
            </div>

            <br>

            <div class="box-element">
                <div class="cart-row">
                    <div style="flex:2"></div>
                    <div style="flex:2"><strong>Item</strong></div>
                    <div style="flex:1"><strong>Price</strong></div>
                    <div style="flex:1"><strong>Quantity</strong></div>
                    <div style="flex:1"><strong>Total</strong></div>
                </div>
                {% for  item in items %}
                <div class="cart-row">
                    <div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
                    <div style="flex:2"><p>{{item.product.name}}</p></div>
                    <div style="flex:1"><p>₹ {{item.product.price|floatformat:2}}</p></div>
                    <div style="flex:1">
                        <p class="quantity">{{item.quantity}}</p>
                        <div class="quantity">
                            <img class="chg-quantity" src="{% static  'store/arrow-up.png' %}">
                    
                            <img class="chg-quantity" src="{% static  'store/arrow-down.png' %}">
                        </div>
                    </div>
                    <div style="flex:1"><p>₹ {{item.get_total}}</p></div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

store/templates/store/checkout.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
<div class="row">
	<div class="col-lg-6">
		<div class="box-element" id="form-wrapper">
               <form id="form">
                    <div id="user-info">
                         <div class="form-field">
                              <input required class="form-control" type="text" name="name" placeholder="Name..">
                         </div>
                         <div class="form-field">
                              <input required class="form-control" type="email" name="email" placeholder="Email..">
                         </div>
                    </div>
                    
                    <div id="shipping-info">
                         <hr>
                         <p>Shipping Information:</p>
                         <hr>
                         <div class="form-field">
                              <input class="form-control" type="text" name="address" placeholder="Address..">
                         </div>
                         <div class="form-field">
                              <input class="form-control" type="text" name="city" placeholder="City..">
                         </div>
                         <div class="form-field">
                              <input class="form-control" type="text" name="state" placeholder="State..">
                         </div>
                         <div class="form-field">
                              <input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
                         </div>
                    </div>
                    <hr>
                    <input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
               </form>
		</div>
          <br>
          <div class="box-element hidden" id="payment-info">
               <small>Paypal Options</small>
          </div>
		
	</div>

	<div class="col-lg-6">
		<div class="box-element">
               <a  class="btn btn-outline-dark" href="{% url 'store:cart' %}">&#x2190; Back to Cart</a>
               <hr>
               <h3>Order Summary</h3>
               <hr>
               {% for  item in items %}
               <div class="cart-row">
                    <div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
                    <div style="flex:2"><p>{{item.product.name}}</p></div>
                    <div style="flex:1"><p>₹ {{item.product.price}}</p></div>
                    <div style="flex:1"><p>x {{item.quantity}}</p></div>
               </div>
               {% endfor %}
               
               <h5>Items:   {{order.get_cart_items}}</h5>
               <h5>Total:    ₹ {{order.get_cart_total|floatformat:2}}</h5>
          </div>
	</div>
</div>
{% endblock content %}

store/templates/store/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> E-commerce </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'store/main.css' %}">
    <script type="text/javascript">
        var user = '{{request.user}}'

        function getToken(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    const csrftoken = getToken('csrftoken');
    </script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'store:store' %}">E-commerce</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'store:store' %}">Store <span class="sr-only">(current)</span></a>
            </li>
       
          </ul>
          <div class="form-inline my-2 my-lg-0">
                <a href="#"class="btn btn-warning">Login</a>
               
                <a href="{% url 'store:cart' %}">
                  <img  id="cart-icon" src="{% static 'store/cart.png' %}">
                </a>
              <p id="cart-total">{{cartItems}}</p>
  
          </div>
        </div>
    </nav>
  
       <div class="container">
            <br>
            {% block content %}


            {% endblock content %}
        </div>



    <!-- JavaScript Bundle with Popper -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  <script type="text/javascript" src="{% static 'store/cart.js' %}"></script>
</body>
</html>

</body>
</html>

store/templates/store/store.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
    <div class="row">
        {% for product in products %}
        <div class="col-lg-4">
            <img class="thumbnail" src="{{product.imageURL}}">
            <div class="box-element product">
                <h6><strong>{{product.name}}</strong></h6>
                <hr>
        
                <button data-product={{product.id}} data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
                <a class="btn btn-outline-success" href="#">View</a>
                <h5 style="display: inline-block; float: right"><strong>₹ {{product.price}}</strong></h5>
        
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock content %}